# Hugolify content available https://www.hugolify.io/docs/sections/

imports:
  # Specific Realestatify
  - path: github.com/hugolify/realestatify-theme
  - path: github.com/hugolify/realestatify-netlify-cms

  # Sections modules 
  - path: github.com/hugolify/hugolify-theme-places
  - path: github.com/hugolify/hugolify-theme-persons-places
  - path: github.com/hugolify/hugolify-theme-persons
  - path: github.com/hugolify/hugolify-theme-realestates
  - path: github.com/hugolify/hugolify-theme-realestates-categories
  - path: github.com/hugolify/hugolify-theme-realestates-persons

  # Core theme
  - path: github.com/hugolify/hugolify-theme

  # CMS
  - path: github.com/hugolify/hugolify-netlify-cms
