# Hugolify content available https://github.com/Hugolify/hugolify-template/wiki/Content-sections

imports:
- path: github.com/hugolify/realestatify-example-site
- path: github.com/hugolify/realestatify-theme
- path: github.com/hugolify/realestatify-netlify-cms
- path: github.com/hugolify/hugolify-theme-places
- path: github.com/hugolify/hugolify-theme-persons-places
- path: github.com/hugolify/hugolify-theme-persons
- path: github.com/hugolify/hugolify-theme-realestates
- path: github.com/hugolify/hugolify-theme-realestates-persons
- path: github.com/hugolify/hugolify-theme-realestates-types
- path: github.com/hugolify/hugolify-theme
- path: github.com/hugolify/hugolify-netlify-cms

