# Hugolify content available https://www.hugolify.io/docs/sections/

imports:
  # Specific Realestatify
  - path: github.com/hugolify/realestatify-example-site

  # For exampleSite
  - path: github.com/hugolify/hugolify-theme-places
  - path: github.com/hugolify/hugolify-theme-persons-places
  - path: github.com/hugolify/hugolify-theme-persons
  - path: github.com/hugolify/hugolify-theme-realestates-categories
  - path: github.com/hugolify/hugolify-theme-realestates-persons
  - path: github.com/hugolify/hugolify-theme-realestates

  # Core theme
  - path: github.com/hugolify/hugolify-theme
