# Hugolify content available https://www.hugolify.io/docs/sections/

imports:
  # Specifi Realestatify
  - path: github.com/hugolify/realestatify-example-site
  - path: github.com/hugolify/realestatify-netlify-cms

  # Theme 3
  - path: github.com/hugolify/hugolify-theme-1

  # Sections modules
  - path: github.com/hugolify/hugolify-theme-places
  - path: github.com/hugolify/hugolify-theme-persons-places
  - path: github.com/hugolify/hugolify-theme-persons
  - path: github.com/hugolify/hugolify-theme-realestates
  - path: github.com/hugolify/hugolify-theme-realestates-categories
  - path: github.com/hugolify/hugolify-theme-realestates-persons

  # Core theme
  - path: github.com/hugolify/hugolify-theme

  # CMS
  - path: github.com/hugolify/hugolify-netlify-cms
